name: Install and Run Ansible
description: Install Ansible and run playbook

inputs:
  ssh_private_key:
    required: true
  remote_host_ip:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Ansible and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-add-repository --yes --update ppa:ansible/ansible
        sudo apt-get install -y ansible sshpass python3-pip
      shell: bash

    - name: Add SSH Key and Host
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/democentralcanada.pem
        chmod 600 ~/.ssh/democentralcanada.pem
        ssh-keyscan -H ${{ inputs.remote_host_ip }} >> ~/.ssh/known_hosts
      shell: bash

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/node_service.yml \
          -i ansible/inventory.ini \
          --private-key ~/.ssh/democentralcanada.pem
      shell: bash
