name: Run Selenium Tests
description: Executes Selenium test with Mocha and generates Mochawesome report

inputs:
  ssh_private_key:
    required: true
  remote_host_ip:
    required: true

runs:
  using: "composite"
  steps:
    - name: Add SSH key and known hosts
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/selenium.pem
        chmod 600 ~/.ssh/selenium.pem
        ssh-keyscan -H ${{ inputs.remote_host_ip }} >> ~/.ssh/known_hosts

    - name: Run Selenium Test on Remote EC2
      shell: bash
      run: |
        ssh -i ~/.ssh/selenium.pem -o StrictHostKeyChecking=no ubuntu@${{ inputs.remote_host_ip }} << 'EOF'
          set -e  # Exit on any error

          # Start Selenium standalone Chrome container if not running
          if [ "\$(docker ps -q -f name=selenium-standalone)" = "" ]; then
            if [ "\$(docker ps -aq -f status=exited -f name=selenium-standalone)" != "" ]; then
              echo "Starting existing selenium-standalone container..."
              docker start selenium-standalone
            else
              echo "Running new selenium-standalone container..."
              docker run -d -p 4444:4444 --name selenium-standalone selenium/standalone-chrome
            fi
          else
            echo "Selenium container already running."
          fi

          # Run the test
          cd ~/test-project
          npx mocha test.mjs --reporter mochawesome
        EOF
