name: Run Selenium Tests
description: Executes Selenium test with Mocha and generates Mochawesome report

inputs:
  ssh_private_key:
    required: true
  remote_host_ip:
    required: true

runs:
  using: "composite"
  steps:
    - name: Add SSH key and known hosts
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/selenium.pem
        chmod 600 ~/.ssh/selenium.pem
        ssh-keyscan -H ${{ inputs.remote_host_ip }} >> ~/.ssh/known_hosts

    - name: Run Selenium Test on Remote EC2
      shell: bash
      run: |
        ssh -i ~/.ssh/selenium.pem -o StrictHostKeyChecking=no ubuntu@${{ inputs.remote_host_ip }} << 'EOF'
  set -e

  # Start Selenium standalone Chrome container if not running
  if [ "$(sudo docker ps -q -f name=selenium-standalone)" = "" ]; then
    if [ "$(sudo docker ps -aq -f status=exited -f name=selenium-standalone)" != "" ]; then
      echo "Starting existing selenium-standalone container..."
      sudo docker start selenium-standalone
    else
      echo "Running new selenium-standalone container..."
      sudo docker run -d -p 4444:4444 --name selenium-standalone selenium/standalone-chrome
    fi
  else
    echo "Selenium container already running."
  fi

  # Move test.mjs from node-app to test-project if it exists
  if [ -f ~/node-app/test.mjs ]; then
    mv ~/node-app/test.mjs ~/test-project/
    echo "test.mjs moved to test-project"
  else
    echo "test.mjs not found in node-app"
    exit 1
  fi

  # Run the test
  cd ~/test-project
  ls -la
  npx mocha test.mjs --reporter mochawesome
EOF
