---
- name: Setup Node.js testing environment with Chrome and Selenium
  hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - curl
          - gnupg
          - unzip
          - ca-certificates
        state: present

    - name: Add Google Chrome GPG key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome

  tasks:
    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Download ChromeDriver (match with installed Chrome version)
      get_url:
        url: https://chromedriver.storage.googleapis.com/126.0.6478.57/chromedriver_linux64.zip
        dest: /tmp/chromedriver.zip

    - name: Unzip ChromeDriver
      unarchive:
        src: /tmp/chromedriver.zip
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'

    - name: Ensure test project directory exists
      file:
        path: /home/ubuntu/test-project
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Initialize npm project (if not exists)
      shell: |
        cd /home/ubuntu/test-project && npm init -y
      args:
        creates: /home/ubuntu/test-project/package.json

    - name: Install test dependencies
      shell: |
        cd /home/ubuntu/test-project && \
        npm install --save-dev mocha chai selenium-webdriver mochawesome
      args:
        chdir: /home/ubuntu/test-project

    - name: Verify Mocha installation
      command: npx mocha --version
      args:
        chdir: /home/ubuntu/test-project
