    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install Chrome browser (for headless testing)
      apt:
        name: google-chrome-stable
        state: present
      vars:
        ansible_debian_no_prompt: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
      pre_tasks:
        - name: Add Google Chrome GPG key
          apt_key:
            url: https://dl.google.com/linux/linux_signing_key.pub
            state: present

        - name: Add Google Chrome repository
          apt_repository:
            repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
            state: present
            filename: google-chrome

    - name: Install ChromeDriver (matching version)
      get_url:
        url: https://chromedriver.storage.googleapis.com/126.0.6478.57/chromedriver_linux64.zip
        dest: /tmp/chromedriver.zip

    - name: Unzip ChromeDriver
      unarchive:
        src: /tmp/chromedriver.zip
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'

    - name: Create project directory if not exists
      file:
        path: /home/ubuntu/test-project
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create package.json if not exists
      shell: |
        cd /home/ubuntu/test-project && npm init -y
      args:
        creates: /home/ubuntu/test-project/package.json

    - name: Install test dependencies
      shell: |
        cd /home/ubuntu/test-project && \
        npm install --save-dev mocha chai selenium-webdriver mochawesome
