name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
            
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}
          TF_VAR_key_name: "democentralcanada"  # your existing key name

      - name: Debug Terraform Output
        run: terraform output
        working-directory: ./terraform          

      - name: Update Ansible Inventory with Terraform IP
        working-directory: ./terraform
        id: get_ip
        run: |
          IP=$(terraform output -raw public_ip)
          if [ -z "$IP" ]; then
            echo "ERROR: No IP from Terraform."
            exit 1
          fi
          echo "::set-output name=ip::$IP"
          echo "[nodejs-app]" > ../ansible/inventory.ini
          echo "$IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/democentralcanada.pem" >> ../ansible/inventory.ini

      - name: Add server SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ steps.get_ip.outputs.ip }} >> ~/.ssh/known_hosts

      - name: Install Ansible and SSH dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible sshpass python3-pip

      - name: Setup SSH Key and Run Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/democentralcanada.pem
          chmod 600 ~/.ssh/democentralcanada.pem
          # Remove the StrictHostKeyChecking line below if using known_hosts
          # echo "StrictHostKeyChecking=no" >> ~/.ssh/config

          ansible-playbook ansible/node_service.yml -i ansible/inventory.ini --private-key ~/.ssh/democentralcanada.pem
