name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
            
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}
          TF_VAR_key_name: "democentralcanda"  # your existing key name

      - name: Update Ansible Inventory with Terraform IP
        run: |
          IP=$(terraform output -raw public_ip -state=./terraform/terraform.tfstate)
          echo "[nodejs-app]" > ansible/inventory.ini
          echo "$IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/democentralcanda.pem" >> ansible/inventory.ini

      - name: Install Ansible and SSH dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible sshpass python3-pip

      - name: Setup SSH Key and Run Ansible
        run: |
          mkdir -p ~/.ssh
          # Copy your PEM key from repo or secrets to the runner's ~/.ssh directory
          cp D:/new_project_windows_runner/.ssh/democentralcanda.pem ~/.ssh/democentralcanda.pem
          chmod 600 ~/.ssh/democentralcanda.pem
          echo "StrictHostKeyChecking=no" >> ~/.ssh/config

          ansible-playbook ansible/node_service.yml -i ansible/inventory.ini --private-key ~/.ssh/democentralcanda.pem
