name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set working directory
        run: cd nodejs-app
      
      - name: Install dependencies
        working-directory: nodejs-app
        run: npm install

      - name: Build
        working-directory: nodejs-app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_public_key: ${{ secrets.EC2_PUB_KEY }}
          TF_VAR_key_name: "ansible-key"

      - name: Install Ansible and SSH dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible sshpass python3-pip

      - name: Setup SSH
        run: |
          echo "${{ secrets.HOST_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run Ansible Playbook
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook ansible/node_service.yml -i ansible/inventory.ini --private-key key.pem

