name: Deploy Node.js App in staging 

on:
  push:
    branches:
      - staging
jobs:
  SeleniumTest:
     runs-on: [self-hosted, linuxRunner]
     steps:
      - name: Create empty test report file
        run: echo "" > mochawesome.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report 
          path: mochawesome.html
      


          
