name: Setup and Apply Terraform
description: Install Terraform and apply infrastructure
runs:
  using: "composite"
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init
      shell: bash
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      shell: bash
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}
        TF_VAR_key_name: "democentralcanada"
